[tools]
bat = "latest"
clojure = "latest"
elixir = "latest"
erlang = "latest"
fd = "latest"
flutter = "latest"
fzf = "latest"
go = "latest"
java = "17"
jq = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
lua = "latest"
neovim = "latest"
node = "latest"
pnpm = "latest"
poetry = "latest"
python = "latest"
ripgrep = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
vivid = "latest"
yarn = "latest"
yazi = "latest"
zig = "latest"
zoxide = "latest"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]
